name :  Deploy NodeJs Application to Hostinger

on : 
   push : 
     branches : 
         - main

jobs : 
  deploy :
     runs-on : ubuntu-latest


     steps : 
       - name : Checkout Code
         uses : actions/checkout

       - name : Deploy Via SSH
         uses : appleboy/ssh-action@v1.8.3
         with : 
           host : ${{ secrets.SSH_HOST}}
           username : roort
           key : ${{ secrets.SSH_KEY}}
           script : | 
           cd /root/short-url
           git pull
           docker componse up -d --build